import Plant from './Plant';

const plants = [
  new Plant("Salal (Gaultheria shallon)", "Salal is a mid-sized, woody shrub with thick, leathery leaves. Berries are arranged along an elongated “branch” that is sticky to the touch. In the late summer, the berries mature. Mature berries are dark purple, almost black, and slightly sticky. The berries taste like a cross between blueberries and blackcurrants. Salal also has other uses– for example, the leaves can be chewed as a hunger suppressant, and can also be curled into a cone for sipping water from!"),
  new Plant("Himalayan Blackberry (Rubus armeniacus)", "This plant grows as a woody vine that clumps together in dense thickets. The leaves are often grouped in pairs of five, with toothed margins. The sweet, black berries are arranged haphazardly around the plant. Watch out for the thorns present along the length of the branches. This should be a familiar plant, as it is found along nearly every trail, highway, and bare spot of ground in Washington!"),
  new Plant("Red Huckleberry (Vaccinium parvifolium)", "The red huckleberry is a deciduous shrub with small, flat, oval-shaped leaves and thin stems. The berries are small and round, and when they ripen in the summer, their berries are bright red. They taste mildly acidic, with some comparing the taste to a tart blueberry. WARNING: Ensure that the leaves are broad and flat, not needle-like. Similar plants with needle-like leaves are actually yew, and the berries of yew are poisonous to humans. Yew berries also have square indentations at the apex of the berries– if your berries have this indicator, DO NOT consume them. "),
  new Plant("Salmonberry (Rubus spectabilis)", "The salmonberry is delightful for the birds, and some humans find them equally delicious. The salmonberry is a prickly shrub, often growing in wet sites such as near streams or at the base of hills. The leaves resemble that of raspberry or blackberry leaves, with roughly 3 to five leaflets for each leaf unit, each having serrated or “toothed” edges. The bark of the salmonberry sometimes peels off, and the prickles can often be easily removed by rubbing a stick against the salmonberry stem. The berries ripen in late spring to early summer, and when ripe they are bright yellow, orange, or red berries that are similar in appearance to blackberries. Many compare the taste of the fruits to that of raspberries. "),
  new Plant("Thimbleberry (Rubus parviflorus)", "The thimbleberry bears deep red, tart and honey-flavored fruit in late spring and early autumn, which are particularly attractive to birds in this area. The thimbleberry plant is a shrub, but unlike its siblings in the Rubus genus, it bears no thorns along its stem (great news for hikers!). The leaves are shaped somewhat like stars, and they are covered in small hairs that make them feel fuzzy when you pet them. For those of you wanting to pick for a large number of people, or to pick a lot of these berries to use in jams or the like, know that they ripen from light pink to red when kept in storage for 1-3 days, so you can pick them slightly prematurely and they’ll be ripe by the time you use them!"),
  new Plant("Broadleaf Plantain (Plantago major)", "Common plantain, also known as broadleaf plantain, is a small and often overlooked foraging food that can be found in disturbed grassy areas and a variety of other sites. They are easily identified by their leaves, which are broad and oval-to-egg-shaped, with prominent parallel veins running the length of the leaf. Young leaves of the common plantain can be eaten raw, with an earthy, grassy, and sometimes peppery taste. The roots and flowers have the same, but slightly milder and sweeter, flavor profile. "),
  new Plant("Wood Sorrel (Oxalis spp.)", "Often mistaken for clover, this small groundcover plant can serve as an excellent addition to mixed green salads. Its leaves are made up of three heart-shaped and folded leaflets, sometimes with a darker color forming a ring spanning the three leaflets. All parts of this plant are edible, so dig in!  WARNING: The oxalic acid that gives wood sorrel its tangy and sour taste also inhibits calcium absorption in large enough quantities, though this should not be an issue for most people. Those with gout, rheumatic conditions, and a history of kidney stones should not consume this plant. "),
  new Plant("Fireweed (Chamaenerion angustifolium)", "This plant is tough to miss. Often present in disturbed sites, this herbaceous plant stands relatively tall, with distinctive inflorescences of bright pink edible flowers. If caught early enough in the season, the young shoots and leaves are palatable, but are edible regardless of the time of harvest. The pith within the stems can be added as a thickening agent to soups, stews, and gravies. The leaves have a light green central vein down each of them. WARNING: May have a laxative effect if eaten in large quantities. "),
  new Plant("Miner’s Lettuce (Claytonia perfoliata)", "This plant is so named because of its historical importance as a salad green for miners in this area during the gold rush. The leaves are edible raw, and they encircle the stem to form a lip-shaped or circular “cup” . The plant itself grows in damp places, including by bodies of water and within forests that get a lot of rainfall. The plant reminds most individuals of spinach when eaten. "),
  new Plant("Bigleaf Maple (Acer macrophyllum)", "Easy to identify due to the distinctively lobed, maple leaf shape and the bright yellow flowers, this tree provides a light snack to those who are tall enough to grab one of its branches. The flower clusters, which emerge in the spring, are reported to have a taste reminiscent of broccoli or sugar peas and make an excellent addition to salads!"),
  new Plant("Oso Berry (Oemleria cerasiformis)", "The Oso berry is a shrub or small tree that flowers in early spring and bears ripened fruits in the summer. The plant is common in moist soils, though can also be found regularly in woodlands and in clearcut areas. The leaves of this plant are oval, but slightly wider towards the apex, and produce a strong cucumber-y smell when crushed (and taste like cucumbers when chewed). The berries hang in clusters, somewhat like grape clusters, and ripen to a deep black with a whitish bloom. When fully ripe, the berries taste of almonds, though may be astringent and bitter when not fully ripened. Be careful to not forget the presence of the large pit within the fruits!"),
  new Plant("Oregon grape (Berberis aquifolium)", "The oregon-grape is a shrub with glossy, opposite, evergreen leaves shaped like those of holly trees. They are almost as prickly, so watch out! If peeled, the inner bark is yellow (which is why the bark was used to make yellow dyes). Flowers are also bright yellow and rather distinctive, but it’s the berries we’re interested in. The berries, blue or black when ripe, are covered in a whitish bloom that is easily rubbed away. They ripen in mid to late summer, and taste rather tart. WARNING: Do not eat in large quantities. Native Americans used this as a cure for shellfish poisoning, but the drug is very potent and therefore should only be consumed in small quantities. "),
  new Plant("Licorice Fern (Polypodium glycyrrhiza)", "Although not a particularly substantial food, the licorice fern can be a tasty treat to hikers who know how to identify it. These ferns can grow in a variety of places, including on rock faces, in trees as an epiphyte, and anywhere else that moss could make a home. Be careful not to confuse this plant for other ferns– one way to ensure that you identify it properly is to look at the leaflets on each frond and compare the shape to the examples below. As with every plant we feature, do not consume unless you are confident in your identification! The roots and very young shoots of this plant give it its name, as they taste strongly of licorice. If that’s a flavor you find palatable, munch on the roots and enjoy!"),
  new Plant("Cleavers", "One of the easiest plants to identify in our flora– simply pluck off a stem and press it against your clothes! Cleavers get their name because they “cleave” to your clothes (that is, they cling and don't let go). This plant is rich in vitamin C, and is best eaten in small quantities before the plant fruits (otherwise, it can act as a laxative). The raw plant is unremarkable and has a very light flavor, but it tastes pleasant when cooked. The leaves are arranged around the stem in circles, like spokes on a wheel, and have small hooked hairs on them which allow the plant to cling to you. "),
  new Plant("Purple Archangel (Lamium purpureum)", "Red deadnettle isn’t going to sting you– it’s a dead nettle, and unlike its siblings, it has no spines to harm you with. The red deadnettle is common in a great variety of settings, and occurs alongside grasses and other groundcover plants in most areas. The flowers are pale to bright pink and are hidden among many heart-shaped, toothed, and slightly fuzzy leaves that become more purple as you go up the stem. All parts of the plant are edible, and many use them as a colorful addition to their salads. It tastes peppery, though some describe the taste as slightly bitter. The stems are square due to its membership in the mint family. "),
  new Plant("White Clover (Trifolium repens)", "Found in many grassy and disturbed sites, the clover is common and blooms in the late summer to early autumn. The pink-tinged white flowers form densely clustered head-like inflorescences above the vegetative parts. The leaves are comprised of three (or if you’re lucky, four) egg-shaped leaflets, with small white or light-green detailing towards the middle of each leaflet. All parts of the clover are edible raw, though some think the seeds are unpalatable. WARNING: For some, consuming clover may cause bloating. "),
  new Plant("Common Dandelion (Taraxacum officinale)", "This common weed is often taken for granted, but in supermarkets you might find its leaves in a bag of mixed greens. It’s a small plant, with a stem that leaks milky sap when broken. The flowers are bright yellow and puffy, almost like a pom-pom, and are edible! The whole plant has historically been used to brew beer, and the roots can be dried and ground for use as a coffee replacement. Further, the roots can be used as a vegetable, and the leaves (of course) can be used in salads."),
  new Plant("Bittercress (Cardimine spp.)", "This herbaceous plant is edible raw, and is reported to have a peppery taste. It grows in moist woods. It is in the mustard family, and therefore shares certain characteristics with other mustard plants, including four-parted flowers and long, slender fruits (called siliques) that hold many seeds within. The leaves are deeply lobed so as to look divided, and in some species are only in a basal rosette (meaning the leaves are clustered around the bottom with none on the stem)."),
  new Plant("Kinnikinnick (Arctostaphylos uva-ursi)", "Kinnikinnick is a woody, vine-like plant that grows in dense thickets upon dry and well-drained soils. The bright red, apple-like berries ripen in late summer and persist until early winter. They are very mild in flavor, but were an important food source due to their longevity. The leaves were smoked by indigenous peoples (though apparently not until after contact with colonizers)."),
  new Plant("Bulrush (Scirpus spp.)", "These sedges have sharply triangular stems and grow in shallow, calm waters. They commonly occur in two varieties: hard-stemmed and soft-stemmed. The shoots and stalks of this plant, as well as the root tips, can be eaten raw or cooked. They are said to taste like asparagus."),
];

export default plants;